export const PERMISSION_DEFINITIONS: { resource: string; actions: string[] }[] = [
  { resource: 'command', actions: ['read'] },
  { resource: 'projects', actions: ['read', 'create', 'update', 'delete', 'manage', 'export'] },
  { resource: 'clients', actions: ['read', 'create', 'update', 'delete', 'manage', 'export'] },
  { resource: 'creative', actions: ['read', 'create', 'update', 'delete', 'manage'] },
  { resource: 'finance', actions: ['read', 'create', 'update', 'delete', 'manage', 'export'] },
  { resource: 'team', actions: ['read', 'create', 'update', 'delete', 'manage'] },
  { resource: 'memory', actions: ['read', 'create', 'update', 'delete'] },
  { resource: 'agents', actions: ['read', 'create', 'update', 'delete', 'execute', 'manage'] },
  { resource: 'settings', actions: ['read', 'update', 'manage'] },
  { resource: 'audit', actions: ['read', 'export'] },
  { resource: 'integrations', actions: ['read', 'create', 'update', 'delete', 'manage'] },
  { resource: 'automations', actions: ['read', 'create', 'update', 'delete', 'execute'] },
  { resource: 'workflows', actions: ['read', 'create', 'update', 'delete', 'execute'] },
  { resource: 'api_keys', actions: ['read', 'create', 'delete', 'manage'] },
  { resource: 'billing', actions: ['read', 'manage'] },
  { resource: 'desktop', actions: ['execute', 'manage'] },
];

export function allPermissionKeys(): string[] {
  return PERMISSION_DEFINITIONS.flatMap((d) => d.actions.map((a) => `${d.resource}:${a}`));
}

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  ADMINISTRATOR: allPermissionKeys().filter(
    (k) => !k.startsWith('billing:manage') && k !== 'settings:manage',
  ),
  CREATIVE_HEAD: [
    'command:read',
    'projects:read',
    'projects:create',
    'projects:update',
    'projects:manage',
    'clients:read',
    'clients:create',
    'clients:update',
    'creative:read',
    'creative:create',
    'creative:update',
    'creative:delete',
    'creative:manage',
    'finance:read',
    'team:read',
    'memory:read',
    'memory:create',
    'memory:update',
    'agents:read',
    'agents:execute',
    'settings:read',
  ],
  DESIGNER: [
    'command:read',
    'projects:read',
    'projects:update',
    'creative:read',
    'creative:create',
    'creative:update',
    'memory:read',
    'agents:read',
    'agents:execute',
  ],
  DEVELOPER: [
    'command:read',
    'projects:read',
    'projects:update',
    'memory:read',
    'memory:create',
    'memory:update',
    'agents:read',
    'agents:execute',
    'agents:manage',
    'settings:read',
    'integrations:read',
    'automations:read',
    'automations:create',
    'automations:update',
    'automations:execute',
    'workflows:read',
    'workflows:create',
    'workflows:update',
    'workflows:execute',
    'desktop:execute',
    'desktop:manage',
  ],
  INTERN: ['command:read', 'projects:read', 'creative:read', 'memory:read'],
  GUEST: ['command:read'],
};
